apiVersion: apps/v1
kind: Deployment
metadata:
  name: shareconfig-deployment
  labels:
    app: shareconfig
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shareconfig
  template:
    metadata:
      labels:
        app: shareconfig
    spec:
      containers:
      - name: shareconfig
        image: atakanyenel/shareconfig-server:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: shareconfig-service
spec:
  selector:
    app: shareconfig
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
