apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: green-daemon
  namespace: default
  labels:
    unikernel: "true"

spec:
  selector:
    matchLabels:
      name: green-daemon
  template:
    metadata:
      labels:
        name: green-daemon

    spec:
      containers:
        - name: sayer
          image: led-daemon
          args:
            - YELLOW
      nodeSelector:
          type: virtual-kubelet
      tolerations:
      - key: "virtual-kubelet.io/provider"
        operator: "Equal"
        value: "unikernel"
        effect: "NoSchedule"


