---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: node-watcher
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list","get","delete","watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: node-watcher
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: ClusterRole
  name: node-watcher
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-watcher
spec:
  selector:
    matchLabels:
      app: node-watcher
  template:
    metadata:
      labels:
        app: node-watcher
    spec:
      containers:
      - name: node-watcher
        image: atakanyenel/vk-node-watcher
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
