apiVersion: v1
kind: Pod
metadata:
  name: command-demo
  labels:
    purpose: demonstrate-command
spec:
  containers:
    - name: curl-pod
      image: radial/busyboxplus:curl
      command: ["curl"]
      args: ["http://10.32.0.12"]
  restartPolicy: OnFailure