apiVersion: v1
kind: Pod
metadata:
  name: pod-n
  labels:
    app: nginx

spec:
  containers:
    - name: nginx-pod
      image: nginxdemos/hello
      ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: nginx