apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURDVENDQWZHZ0F3SUJBZ0lVWUhKdXU3aUdSRW0xaTAvdGJmUnkzQzJJVEQ0d0RRWUpLb1pJaHZjTkFRRUwKQlFBd0ZERVNNQkFHQTFVRUF3d0pNVEkzTGpBdU1DNHhNQjRYRFRFNU1EZ3lNakl5TURneE0xb1hEVFEzTURFdwpOekl5TURneE0xb3dGREVTTUJBR0ExVUVBd3dKTVRJM0xqQXVNQzR4TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGCkFBT0NBUThBTUlJQkNnS0NBUUVBdnFCZmpGVW1uOGpKbkxSWUtFZjdnYkZxZW53N3ltalVoM0w4SGNGSjFwNHkKQThtRHB4TVg5aVNpQ1RNUWdlYzNGeXU5a3EzMlVyL3dESTdFSDM3WjNWclpxaXlPVWJ0a005bExKbGtKUTNmUwpHSkMyY0VxRDVqUWxiYnhGZk1RRUhoYTJ4UWtrYlVoZGwwak1ueHdjSUJkN29aRzYwdFNBUDNIRXEwRlN2RTdoClU5T3JWeFBlZDJhZ2ZsanVkMEZtUEkwcldLU2RVRk56WDl2T3VBT0RabDhyaXN6TTFqQWh1YnphUjQrK1ByanUKbHRub2xVWTlDQm15anVDck81c3MvMVYzQnFJNVp1TlZXNnZaYVB0UmIxY2I0Wm02My9zcWJkR1B4ZEU4OWVpRwpjQWs2U0U1VXllVlFVa3ZlVXJIK3FScXhrY3BQWEd6T3RBSVZOdTVnQlFJREFRQUJvMU13VVRBZEJnTlZIUTRFCkZnUVVGcENhYUMrOC81YzJ1S25rV2JxNFVlYitFV293SHdZRFZSMGpCQmd3Rm9BVUZwQ2FhQys4LzVjMnVLbmsKV2JxNFVlYitFV293RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBUWJlaApHYjBSd3lEMnE3T0ZCakg0b3Bjci9TcnR0amo1bXI4NDNQR3BYTmFPa3RFMm1aeElIRkZFYmRoOTBRNk03dFIvCjRRWldpRGdFYmFpTzY2MWUvejlVVnJxS3VyODRCc2pWejFNNTErNzFRY08yd0F6MVByVHB3QUpxV3YwVmJLT3UKZWMvdFoySUtoM2tjczdqazZDWEtCelR0S3laUW0vM2ErNVAvenJhc1VxR0NwT0E4RFVkSENDMnhqckRVNWQ5cQozNU00WjczVDFJN1dVYVJvSHhoSnZOMlFta0F3T1JLZDFCMG96OGwzZittWVkzRUorUytXUTZManJRZVBmMnYrCkRpd1cwbzU0Zk90RDNnbUxzNWJ3dTFKZCsrZnJBeFBYVGtvWkcyTTdiNThYU2ZQNitqMXoyVk1QK3dSeU13YWkKandWWDUyNkpDeGVIMnNpbDJ3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://192.168.1.235:16443
  name: microk8s-cluster
contexts:
- context:
    cluster: microk8s-cluster
    user: admin
  name: microk8s
current-context: microk8s
kind: Config
preferences: {}
users:
- name: admin
  user:
    password: RzJvSkZrUjNkRmNYbXJ6MGY3d0hVOWc5SThYUFBUTDFPbWhlV1ZFaXpXdz0K
    username: admin
