apiVersion: apps/v1
kind: Deployment
metadata: 
    name: humidity
    labels:
        app: humidity
spec:
    replicas: 1
    selector:
        matchLabels:
            app: humidity
    template:
        metadata:
            labels:
                app: humidity
        spec:
            containers:
            - name: unikernel
              image : echo "sad" > gh
              env:
                - name: "sensor"
                  value: "humidity"
            nodeSelector:
              type: virtual-kubelet
              model: raspberry-pi
            tolerations:
            - key: "virtual-kubelet.io/provider"
              operator: "Equal"
              value: "unikernel"
              effect: "NoSchedule"
