apiVersion: apps/v1
kind: Deployment
metadata: 
    name: unikernel-deployment
    labels:
        app: silly
spec:
    replicas: 3
    selector:
        matchLabels:
            app: silly
    template:
        metadata:
            labels:
                app: silly
        spec:
            containers:
            - name: unikernel
              image : unikernel-image
              ports:
              - containerPort: 4433
            nodeSelector:
              type: virtual-kubelet
            tolerations:
            - key: "virtual-kubelet.io/provider"
              operator: "Equal"
              value: "unikernel"
              effect: "NoSchedule"
